# Generated by Django 3.2.13 on 2022-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('bin', models.BooleanField(blank=True, db_column='BIN', null=True)),
                ('uuid', models.CharField(db_column='UUID', max_length=255, primary_key=True, serialize=False)),
                ('auctioneer', models.CharField(blank=True, db_column='Auctioneer', max_length=255, null=True)),
                ('profileid', models.CharField(blank=True, db_column='ProfileID', max_length=255, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('itemname', models.CharField(blank=True, db_column='ItemName', max_length=255, null=True)),
                ('itemlore', models.CharField(blank=True, db_column='ItemLore', max_length=2555, null=True)),
                ('extra', models.CharField(blank=True, db_column='Extra', max_length=1000, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=155, null=True)),
                ('tier', models.CharField(blank=True, db_column='Tier', max_length=155, null=True)),
                ('startingbid', models.IntegerField(blank=True, db_column='StartingBid', null=True)),
                ('itembytes', models.CharField(blank=True, db_column='ItemBytes', max_length=2555, null=True)),
                ('claimed', models.BooleanField(blank=True, db_column='Claimed', null=True)),
                ('claimedbidders', models.CharField(blank=True, db_column='ClaimedBidders', max_length=255, null=True)),
                ('highestbidamount', models.IntegerField(blank=True, db_column='HighestBidAmount', null=True)),
            ],
            options={
                'db_table': 'Auction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('profileid', models.CharField(blank=True, db_column='ProfileID', max_length=255, null=True)),
                ('bidder', models.CharField(blank=True, db_column='Bidder', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('bidamount', models.IntegerField(blank=True, db_column='BidAmount', null=True)),
            ],
            options={
                'db_table': 'Bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bidtoauction',
            fields=[
                ('bidid', models.IntegerField(db_column='BidID', primary_key=True, serialize=False)),
                ('auctionid', models.CharField(db_column='AuctionID', max_length=255)),
            ],
            options={
                'db_table': 'BidToAuction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeAuction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_auction',
                'managed': False,
            },
        ),
    ]
